spring:
  application:
    name: reserveone

  datasource:
    url: jdbc:postgresql://localhost:5432/reserveone_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-zlaftwwyupwcu8sh.us.auth0.com/
app:
  auth0:
    audience: https://api.reserveone

server:
  port: 8080

logging:
  group:
    sql-init:
      - org.springframework.jdbc.datasource.init.ScriptUtils
      - org.springframework.boot.sql.init
    hibernate-sql:
      - org.hibernate.SQL
  level:
    sql-init: DEBUG
    hibernate-sql: DEBUG
