spring:
  application:
    name: reserveone

  datasource:
    url: jdbc:postgresql://localhost:5432/reserveone_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:reserveone}
    password: ${DB_PASSWORD:CHANGE_ME}

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format-sql: true

server:
  port: 8080

logging:
  group:
    sql-init:
      - org.springframework.jdbc.datasource.init.ScriptUtils
      - org.springframework.boot.sql.init
    hibernate-sql:
      - org.hibernate.SQL
  level:
    sql-init: DEBUG
    hibernate-sql: DEBUG
